export enum Paths {
  Root = '/',
  Dashboard = '/dashboard',
  Templates = '/templates',
  Workspace = '/workspace',
  Editor = '/editor',
  Payment = '/payment',
  AuthSignIn = '/auth/sign-in',
  AuthSignUp = '/auth/sign-up',
  Admin_Users = '/admin/users',
  Admin_Statistic = '/admin/statistic',
  Admin_History = '/admin/history',
  Admin_Services_Control = '/admin/services-control',
  Admin_Form_Builder = '/admin/services-control/form-builder/:id',
}